"""autogenerated migration

Revision ID: 1e9fc9bbb64f
Revises: c6ad43b27e7c
Create Date: 2024-06-27 00:11:12.242893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9fc9bbb64f'
down_revision: Union[str, None] = 'c6ad43b27e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
