"""Corutine_Prefix

Revision ID: c6ad43b27e7c
Revises: aa68c8a82893
Create Date: 2024-06-06 17:27:26.543670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ad43b27e7c'
down_revision: Union[str, None] = 'aa68c8a82893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
